source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_frameworks!

target 'JKPresentationControllerDemo' do

pod 'JKPresentationController', '~> 1.0.0'
pod 'SnapKit', '~> 5.0.0'
pod 'FDFullscreenPopGesture', '~> 1.1'

end
